
package ch.bfh.ti.sed.patmon1.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoginControllerService", targetNamespace = "http://ch/bfh/ti/sed/patmon1/ws/", wsdlLocation = "http://localhost:8888/login?wsdl")
public class LoginControllerService
    extends Service
{

    private final static URL LOGINCONTROLLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.bfh.ti.sed.patmon1.ws.LoginControllerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ch.bfh.ti.sed.patmon1.ws.LoginControllerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/login?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/login?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGINCONTROLLERSERVICE_WSDL_LOCATION = url;
    }

    public LoginControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginControllerService() {
        super(LOGINCONTROLLERSERVICE_WSDL_LOCATION, new QName("http://ch/bfh/ti/sed/patmon1/ws/", "LoginControllerService"));
    }

    /**
     * 
     * @return
     *     returns LoginControllerPort
     */
    @WebEndpoint(name = "LoginControllerPort")
    public LoginControllerPort getLoginControllerPort() {
        return super.getPort(new QName("http://ch/bfh/ti/sed/patmon1/ws/", "LoginControllerPort"), LoginControllerPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginControllerPort
     */
    @WebEndpoint(name = "LoginControllerPort")
    public LoginControllerPort getLoginControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ch/bfh/ti/sed/patmon1/ws/", "LoginControllerPort"), LoginControllerPort.class, features);
    }

}
